#Name: api

#Ports:
#Port: 8000
#HealthPort: 9300
#MetricsPort: 9400

#Prefix:
#RestPrefix: "/rest"
#WebsocketPrefix: "/ws"
#HealthPrefix: "/health"
#MetricsPrefix: "/metrics"

#Monitoring:
#HealthPollingInterval: 10
#LogLevel: "DEBUG"
#LogToFile: false
#NetworkName: "mainnet"

#Kafka:
#KafkaBrokerURL: "kafka:29092"
#SchemaRegistryURL: "schemaregistry:8081"
#KafkaGroupID: "api-group"

#Topics:
#  ConsumerTopics:
#    - "blocks"
#  ProducerTopics:
#    - "blocks-ws"
#  SchemaNames:
#    blocks: "block_raw"
#    blocks-ws: "block_raw"

#Postgres:
#  host: "postgres"
#  port: 5432
#  user: "postgres"
#  password: "changeme"
#  dbname: "postgres"
#  sslmode: "disable"
#  timezone: "UTC"

#Mongo:
#  host: "mongo"
#  port: 27017